---

- name: update /etc/hosts
  lineinfile:
    dest=/etc/hosts
    state=present
    regexp='^\s*{{ansible_role_hostname_primary_ip}}\s'
    line="{{hosts_line}}"

- name: update /etc/hostname
  copy:
    dest=/etc/hostname
    content="{{hostname_line}}"

- name: reset hostname
  command: hostname {{ansible_role_hostname_hostname}}
  when: not ansible_role_hostname_hostname==ansible_role_hostname_hostname_old
